### ISSUE TITLE
Having issues with inital connection to Zenoss Device

### ISSUE THREAD

**Issue by tdavison784** [Zuora-TechOps/ZenossAPIClient#17]
Issue:
Trying to establish a connection to our Zenoss device. Getting an error from module: apicleint.py
line: 88 in get_routers method.

Error:
  File "C:\Users\Thomas.Davison1\PycharmProjects\Zenoss_test\venv\lib\site-packages\zenossapi\apiclient.py", line 66, in __init__
    for router in self.get_routers():
  File "C:\Users\Thomas.Davison1\PycharmProjects\Zenoss_test\venv\lib\site-packages\zenossapi\apiclient.py", line 88, in get_routers
    name, ext = fname.split('.')
ValueError: not enough values to unpack (expected 2, got 1)

Expected result:

Should be able to connect and view devices.

Can you assist with this issue?

Thanks!

**Comment by discogestalt** [comment]
I have to admit, I've never tested any of this under Windows. The issue is that `get_routers` is using `os.listdir` to get the list of of files in the `routers` subdirectory in the package. That should only contain:
```
__init__.py
device.py
devicemanagement.py
events.py
jobs.py
monitor.py
properties.py
template.py
```
but it seems on your system it's getting at least one file in the listing that doesn't have an extension. Do you have any extra files in that directory in your install?

**Comment by Kamori** [comment]
It seems python3's __pycache__ dir is causing this problem
